### ISSUE TITLE
Error when attempting to retrieve artwork from file

### ISSUE THREAD

**Issue by SteveDinn** [music-assistant/hass-music-assistant#1108]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

I don't think that missing artwork should constitute an error, it's a warning at best, if even that.

I get that this isn't MA that is actually throwing the exception here, but perhaps it could let the client know that it doesn't have artwork so that the client wouldn't bother trying to retrieve it, or at least retrieve some default artwork instead.

### How to reproduce

Have music without album artwork.
Click on the album in M.A. and you should see the error.

### Relevant log output

```
homeassistant    | 2023-02-28 10:11:10.408 ERROR (MainThread) [aiohttp.server] Error handling request
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
homeassistant    |     resp = await request_handler(request)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
homeassistant    |     resp = await handler(request)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
homeassistant    |     result = await result
homeassistant    |   File "/config/custom_components/mass/panel.py", line 92, in get
homeassistant    |     data = await mass.metadata.get_thumbnail(url, size=size)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/metadata.py", line 260, in get_thumbnail
homeassistant    |     thumbnail = await create_thumbnail(self.mass, path, size)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 45, in create_thumbnail
homeassistant    |     img_data = await get_image_data(mass, path)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 38, in get_image_data
homeassistant    |     raise FileNotFoundError(f"Image not found: {path}")
```

### What version of Home Assistant Core are your running

2023.2.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Errors aren't normally thrown just because artwork is missing. So your steps to reproduce don't work for me. I have plenty of albums with no artwork. Having said this the new version of MA is due soon so you will need to hang onto this and see if it is still an issue after the new release.

**Comment by SteveDinn** [comment]
Cool. I'll wait for the new version.

**Comment by marcelveldt** [comment]
Instead of reporting an error you're spawning your opinion and assumptions ;-)
Ofcourse MA will not raise an exception if an album has no artwork, it would be silly if it would.

Instead its raising because retrieving the artwork for an album is failing.
Do you by any chance have an idea which file is was trying to read and do you spot something when you try to read that file with a tag editor ?

**Comment by SteveDinn** [comment]
When I went to investigate, I realized that I had not copied the last line of the error, and all instances of that error reference the same file. It is definitely not as pervasive an error as I had originally thought.

```
homeassistant    | 2023-02-28 13:31:18.983 ERROR (MainThread) [aiohttp.server] Error handling request
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
homeassistant    |     resp = await request_handler(request)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
homeassistant    |     resp = await handler(request)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
homeassistant    |     result = await result
homeassistant    |   File "/config/custom_components/mass/panel.py", line 92, in get
homeassistant    |     data = await mass.metadata.get_thumbnail(url, size=size)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/metadata.py", line 260, in get_thumbnail
homeassistant    |     thumbnail = await create_thumbnail(self.mass, path, size)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 45, in create_thumbnail
homeassistant    |     img_data = await get_image_data(mass, path)
homeassistant    |   File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 38, in get_image_data
homeassistant    |     raise FileNotFoundError(f"Image not found: {path}")
homeassistant    | FileNotFoundError: Image not found: /media/music/Danko Jones/Wild Cat/11 Revolution (But Then We Make Love).mp3
```

I'm not sure what this error really means, because the file is definitely there, but it is obviously not an image.

Here's the directory listing of the folder where that file lives from within the home assistant container:
```
bash-5.1# ls -lFh "/media/music/Danko Jones/Wild Cat/"
total 90M
-rw-rw-r--    1 1000     1002        8.5M Aug 13  2020 01 I Gotta Rock.mp3
-rw-rw-r--    1 1000     1002        8.7M Aug 13  2020 02 My Little RnR.mp3
-rw-rw-r--    1 1000     1002        8.2M Aug 13  2020 03 Going Out Tonight.mp3
-rw-rw-r--    1 1000     1002        7.9M Aug 13  2020 04 You Are My Woman.mp3
-rw-rw-r--    1 1000     1002        7.5M Aug 13  2020 05 Do This Every Night.mp3
-rw-rw-r--    1 1000     1002        7.5M Aug 13  2020 06 Let's Start Dancing.mp3
-rw-rw-r--    1 1000     1002        8.8M Aug 13  2020 07 Wild Cat.mp3
-rw-rw-r--    1 1000     1002        8.0M Aug 13  2020 08 She Likes It.mp3
-rw-rw-r--    1 1000     1002        8.3M Aug 13  2020 09 Success in Bed.mp3
-rw-rw-r--    1 1000     1002        8.4M Aug 13  2020 10 Diamond Lady.mp3
-rw-rw-r--    1 1000     1002        8.3M Aug 13  2020 11 Revolution (But Then We Make Love).mp3
-rw-rw-r--    1 1000     1002       87.4K Aug 13  2020 cover.jpg
bash-5.1#
```
All the MP3 files have embedded cover art in addition to the `cover.jpg` file in that folder.

Here's a dump of running `ffprobe` on that file mentioned in the error:
```
ffprobe version 4.3.5-0+deb11u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mp3, from '/media/music/Danko Jones/Wild Cat/11 Revolution (But Then We Make Love).mp3':
  Metadata:
    album           : Wild Cat
    artist          : Danko Jones
    album_artist    : Danko Jones
    genre           : Rock
    title           : Revolution (But Then We Make Love)
    track           : 11/11
    date            : 2017
  Duration: 00:03:34.60, start: 0.025056, bitrate: 326 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.99r
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 630x630 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (back)
    Stream #0:2: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

Let me know if there's anything else I can do to help!

**Comment by marcelveldt** [comment]
Hmm, strange, we use ffmpeg to extract the embedded coverart from the file. Not sure why it fails to do so.
I'll lookup the exact syntax so maybe you can give that a shot on the offending file(s)

**Comment by marcelveldt** [comment]
ffmpeg -i FILE_PATH_HERE -map 0:v -c copy -f mjpeg IMAGE_PATH_HERE.JPG

Can you give that command a try to see if it results in an image file ?

**Comment by marcelveldt** [comment]
Oh wait, I look more closely now and see that it could not even find the file at all so it does not even try to extract the image.
I actually changed a lot of that code in the current V2 version I'm working on so good chance I already fixed this but still curious why it failed in the first place. You are 100% sure the file is accessible by the HA process and has sufficient access rights ? Can you play it in MA ?

**Comment by SteveDinn** [comment]
I actually cannot play it in Music Assistant, nor anything else. I hadn't tried to use MA since upgrading to the latest HA core image,and I don't know if that has anything to do with it, but I have not been able to use it since then.

the following are the logs that I see when I try to play something from Music Assistant.
```
2023-02-28 19:10:53.386 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: file://track/dankojonesbornalion03soundoflovemp3 (Danko Jones - Sound Of Love) for queue Kitchen Home - crossfade: False
2023-02-28 19:10:53.601 ERROR (Thread-141) [homeassistant.components.cast.media_player] Failed to cast media http://10.1.1.4:8095/control/media_player.kitchen_home/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2023-02-28 19:10:53.732 ERROR (Thread-141) [homeassistant.components.cast.media_player] Failed to cast media http://10.1.1.4:8095/control/media_player.kitchen_home/next.mp3. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2023-02-28 19:10:54.303 INFO (MainThread) [music_assistant] Finished job [Add file://track/dankojonesbornalion03soundoflovemp3 to database] in 1.39 seconds.
```

Now, 10.1.1.4 is the IP of a computer on my network, but it is not my Home Assistant instance, nor is the IP of the `kitchen_home` media_player. I honestly don't know where it pulled that IP address from.

**Comment by OzGav** [comment]
Firstly MA does not work with the 2023.3.x HA version. If you have upgraded then you will need to wait for the V2 version in a week or so. 
I actually think Marcel meant HA in his post. That is, if you can play the track in HA then it does point to somehting about MA but if it doesn't play in HA either then perhaps something wrong with the track.
In relation to the error above you have some sort of network/HA/MA configuration problem.

**Comment by SteveDinn** [comment]
I am still on Home Assistant 2023.2.5, but I've had more than my share of problems for upgrading to this patch.

**Comment by OzGav** [comment]
I think I have seen some others raising issues with .5. You could try rolling back to 2023.2.4 and see if that helps. However you will still have that config issue to resolve as well.

**Comment by OzGav** [comment]
Refer also to here https://github.com/music-assistant/hass-music-assistant/discussions/709 Specifically the first section and then the section regarding music not playing

**Comment by SteveDinn** [comment]
Thanks! Setting my internal URL fixed the playing issue.
Even rolling back to 2023.2.4, the problem with detecting the cover art still remains.
I shall wait for the next version.

**Comment by OzGav** [comment]
I think Marcel is interested to know if you can play that track in HA though. So if you could try that and let us know that would be great.

**Comment by SteveDinn** [comment]
Yes, I can. Despite not being able to get the cover art, it plays just fine.

**Comment by OzGav** [comment]
OK thanks. If @marcelveldt needs anything further he or we will let you know. Thanks for the report.

**Comment by SteveDinn** [comment]
No, I haven't attempted to upgrade yet...I was waiting for HACS to notify me of a new version, and I'm just now reading that I can run MA in a separate docker container, which I will do later tonight.

**Comment by OzGav** [comment]
Cool. Just remember v2 is in beta so there will be issues. You can keep v1 on your machine as well but you have to disable the integration while using the add on.

**Comment by OzGav** [comment]
@SteveDinn is this fixed in MA2?
