### ISSUE TITLE
v1.1.7: database exception

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#192]
I tried to add a number as 'next' to the playing queue (one that I looked up under artists). 
That failed. Later I noticed this error in the log (so it will be related):
```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:243 
First occurred: 13:20:53 (1 occurrences) 
Last logged: 13:20:53

Job [Add spotify://album/38MklVAM0DEnMCLucNckDD to database] failed with error near "ve": syntax error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 94, in add
    await self._match(db_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 248, in _match
    if await find_prov_match(provider):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 220, in find_prov_match
    search_result = await self.search(searchstr, provider.id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 120, in search
    return await provider.search(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 126, in search
    albums = await self.mass.music.albums.get_db_items(query)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 185, in get_db_items
    return [self.item_cls.from_db_row(db_row) for db_row in await func]
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 105, in get_rows_from_query
    return await _db.fetch_all(query)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 149, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 271, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 93, in fetch_all
    async with self._connection.execute(query_str, args) as cursor:
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/context.py", line 41, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "ve": syntax error

```

**Comment by marcelveldt** [comment]
I just fixed that one today. I'll release a new version asap with the patch

**Comment by erkr** [comment]
Nice 👍 I will continue to report the kind of issues. It works great already! 
Very happy with the Hamburger 🍔!!

**Comment by marcelveldt** [comment]
1.1.8 released. Can you check if the issue is resolved ?

**Comment by erkr** [comment]
No I can still reproduce. For example adding this track gives the same exception:

`http://192.168.178.47:8123/media/MP3_normalized/Various/Typisch%20-%20Tachtig!%20CD4/Mp3/Typisch%20-%2017%20-%20Adam%20&%20The%20Ants.mp3`

Think it is the name with the '&' in it: `Typisch - 17 - Adam & The Ants.mp3.`

Logging:
```

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mass/panel.py:89 
Integration: Music Assistant (documentation, issues) 
First occurred: 18:31:31 (5 occurrences) 
Last logged: 18:33:40

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/mass/panel.py", line 89, in get
    data = await mass.metadata.get_thumbnail(url, size=size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 235, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/images.py", line 37, in create_thumbnail
    raise FileNotFoundError(f"Image not found: {path}")
FileNotFoundError: Image not found: /media/MP3_normalized/Various/Typisch - Tachtig! CD4/Mp3/Typisch - 17 - Adam 


```

**Comment by erkr** [comment]
Solved
