### ISSUE TITLE
"Prepend Notification Sound" option in Configuration not working correctly

### ISSUE THREAD

**Issue by arretx** [music-assistant/hass-music-assistant#2020]
### What version of Music Assistant has the issue?

2.0.0.b114

### What version of the Home Assistant Integration have you got installed?

2024.3.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In hearing a chime sound prior to playing a TTS announcement, I hunted it down to the setting in the Configuration of the integration which has a checkbox to disable "Prepend Notification" when sending to TTS.  The problem is that when I uncheck this box it doesn't save my setting.

### How to reproduce

Try reconfiguring the integration.

### Music Providers

N/A

### Player Providers

N/A

### Full log output

the configuration of the integration doesn't seem to affect the MA Settings >> Core logs.

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by TheWebMachine** [comment]
I'm seeing the same issue. The tone is quite disagreeable to me and I'd love to turn it off. haha

**Comment by marcelveldt** [comment]
This is fixed in HA integration update 2024.3.3

**Comment by TheWebMachine** [comment]
Actually, now it appears stuck in the unchecked position in 2024.3.3. You can check it, submit, and then find it unchecked if you go back into Configure again. I always double-toggle new or repaired features to ensure they are set properly and it won't stay enabled for me. Always unchecked when go back into Configure.

That said, the prepended chime option is being respected and it does not play before the TTS.

**Comment by OzGav** [comment]
Yes confirmed

**Comment by arretx** [comment]
Despite unchecking and saving, the checkmark remains, and the chime remains.  If I look at core.config_entries under .storage, I see the following:

```
{
        "entry_id": "baddc1eaa73736e89842edd5fd890ad0",
        "version": 1,
        "minor_version": 1,
        "domain": "mass",
        "title": "Music Assistant",
        "data": {
          "url": "http://172.30.32.1:8095",
          "expose_players_assist": false,
          "pre_announce_tts": false,
          "openai_agent_id": "homeassistant",
          "use_addon": false,
          "integration_created_addon": false
        }
```
...which suggests that what I saved was written, yet the chime still occurs.

**Comment by OzGav** [comment]
Fixed in Integration 2024.3.4

**Comment by Ixitxachitl** [comment]
I can't find that option as of the latest update to the integration, was it removed?

**Comment by OzGav** [comment]
Its now a per player setting. See the MA SETTINGS>>PLAYER>><player name>>>CONFIGURE>>AUDIO
