### ISSUE TITLE
List of players in "Transfer queue" shows deleted players

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2900]
### What version of Music Assistant has the issue?

2.3.0b19

### What version of the Home Assistant Integration have you got installed?

None

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When deleting a player provider, the associated players continue to show in the "Transfer queue to another player" screen

### How to reproduce

1. Add the Airplay music provider
2. Go to the queue
3. Open the "Transfer queue to another player" screen
4. Notice that there is quite a long list of players, with a scroll bar at the bottom
![image](https://github.com/user-attachments/assets/6d0297d1-848f-455f-b186-9cac95910cf4)
5. In settings, delete the airplay provider
6. Go back to the queue and click on transfer queue once more
7. Observe that the player list is unchanged
![image](https://github.com/user-attachments/assets/b81aca6a-781a-48af-99f5-419642a1e103)
8. Press F5 (if in a desktop browser)
9. Go back to the queue and click on transfer queue once more
10. Observe that the player list is now updated - the deleted players are gone
![image](https://github.com/user-attachments/assets/36f03f60-3d8c-4add-862c-a11630ad07fe)

The issue is that step 8 (refresh page) should not be required.
 

### Music Providers

Qobuz

### Player Providers

Chromecast, Airplay

### Full log output

[ma_refresh.log](https://github.com/user-attachments/files/16970258/ma_refresh.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
should be fixed in 3.2.0b22

**Comment by OzGav** [comment]
@madbrain76 please close this if it has been fixed.

**Comment by madbrain76** [comment]
Well, there was the issue with the one player that rose to the top. It required renaming to fix it. I don't think that should have been needed. The other players didn't require renaming to be sorted. I don't know why the one player was treated differently. I think that should be fixed before closing this issue.

**Comment by OzGav** [comment]
This issue is about deleted players being shown. If that is fixed then this needs to be closed.

As for the other, unless you can recreate it, it is impossible to say why that happened. It doesn’t seem worth expending further effort in trying to work out why when it is a single report and was rectified by renaming.

**Comment by madbrain76** [comment]
Sorry, I had a brain fart last night, I confused the two issues. I just verified that unfortunately, this problem is not fixed . I tested in b23. I removed the DLNA and Airplay players. Then opened the queue, clicked "transfer queue" and they were still all there.

On the other report (unsorted entry), somebody new to MA running into this will not know that renaming is needed, without interacting with devs as I did. I can likely reproduce the issue if it will help fix it.

**Comment by OzGav** [comment]
Ok deleted players still showing will continue to be looked at. As for the other issue if you can reliably recreate it then it will also be looked into further.

**Comment by marcelveldt** [comment]
this should be fixed in 2.3.0b24

**Comment by madbrain76** [comment]
Unfortunately, it's still not fixed in b24 . The refresh is still required. I'm using Firefox 130 on Windows, if that matters.
There is a missing step 0 in the test case - start playing something first.

[music-assistant_deleted_players.log](https://github.com/user-attachments/files/17027984/music-assistant_deleted_players.log)

**Comment by OzGav** [comment]
That might matter. Can you try Chrome?

**Comment by madbrain76** [comment]
I just did. It's broken in Chrome too.

**Comment by OzGav** [comment]
This should b fixed in beta 33 or above. Please confirm.

**Comment by OzGav** [comment]
This will be closed soon due to no followup
