### ISSUE TITLE
Sonos volume increases or decreased by 5% instead of 2%.

### ISSUE THREAD

**Issue by cautious-bread** [music-assistant/hass-music-assistant#3001]
### What version of Music Assistant has the issue?

2.3.0b29

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When adjusting the volume of my Sonos Symfonisk speaker/player via Music Assistant, the increment are 5% instead of 2% as is the case with the buttons directly on the device, via HA or the Sonos app.
This isn't a huge issue, but can be annoying at night when the difference between 5% and10% volume is so noticeable.

### How to reproduce

Adjust the volume, for the Sonos player, via the volume +/- button in Music Assistant, or via buttons mapped to these functions in HA.  Notice the jump is in 5% increments instead of 2%.

### Music Providers

All providers have the issue - Filesystem, Radio Browser, Subsonic.

### Player Providers

I'm only using the Sonos player provider, so unable to see if this is the same across all other players, or just Sonos.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17256286/music-assistant.log)

### Additional information

I've had a look through the UI, so see if there was a way to set the increments manually, but I cannot see any.
Changing the Sonos increments to 2% to match the device and other methods would be ideal, or even have an option to set the increments ourselves (some users may prefer the larger 5% jump).
Running Music Assistant via the HA add-on.  HA is running on a VM within Proxmox.

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@cautious-bread please confirm this is fixed in the latest stable/beta

**Comment by cautious-bread** [comment]
Afraid not.  Just updated to 2.4.0b1 and the volume still jumps in 5% increments.

**Comment by marcelveldt** [comment]
> Afraid not. Just updated to 2.4.0b1 and the volume still jumps in 5% increments.

Its a bit smarter than that. It jumps in small increments on the edges but in larger steps in the middle

**Comment by cautious-bread** [comment]
Hmm, not for me.  I've just updated to 2.4.0b2 and rebooted the server.  I still get 5% jumps all the way from 0% to 100% and back when controlling via MA.

**Comment by marcelveldt** [comment]
Sorry, I missed the controls on the full screen player. This is now fixed (in 2.3.2 / 2.4.0b3)

**Comment by cautious-bread** [comment]
Ah, nice one.  I can see the smaller increments under 10% now, with it larger above 20%.
It reverts to small increments again at 90%.  Not sure if that's intentional.

Thank you.

**Comment by marcelveldt** [comment]
below 5 or above 95 --> step size 1
below 20 or above 80 --> step size 2
anything in between = step size 5
