### ISSUE TITLE
MA will not load

### ISSUE THREAD

**Issue by jscherry** [music-assistant/hass-music-assistant#804]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

After upgrading to 2022.8.1 it wouldn't load MA. I uninstalled MA and reistalled and am still getting KeyError: HA Version?

### How to reproduce

Install MA from add integrations. 

### Relevant log output

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:124
Integration: Music Assistant (documentation, issues)
First occurred: 7:48:46 PM (2 occurrences)
Last logged: 8:19:29 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 124, in async_setup_entry
    manifest["ha_version"],
KeyError: 'ha_version'

### What version of Home Assistant Core are your running

2022.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by xZetsubou** [comment]
it's because of HA 2022.8.1 update you could fix it by going to [temp fix till new release]
/config/custom_components/mass/__init__ .py I think line 109
change vers_parts[1]}.**0** to vers_parts[1]}.**1**
change it from [0] to [1] 
![image](https://user-images.githubusercontent.com/46300268/182985639-d1ac8a2a-c2a5-4945-88e4-da9ecf8e0524.png)

**Comment by aquarius15283** [comment]
> it's because of HA 2022.8.1 update you could fix it by going to /config/custom_components/mass/**init** .py I think line 109 change vers_parts[1]}.**0** to vers_parts[1]}.**1** change it from [0] to [1] ![image](https://user-images.githubusercontent.com/46300268/182985639-d1ac8a2a-c2a5-4945-88e4-da9ecf8e0524.png)

It worked. Many thanks

**Comment by jurgenhaas** [comment]
Same here.

Q: Does the version constraint have to be that strict?

**Comment by marcelveldt** [comment]
Fix is on the way!

**Comment by marcelveldt** [comment]
I have just released MA version 2022.8.1 which fixes the wrong code on the version check.

@jurgenhaas No the version check does not need to be that strict, the code as just plain wrong. I guess it was late when I wrote that :-)

**Comment by gelokatil** [comment]
Thanks! @marcelveldt

**Comment by jurgenhaas** [comment]
Great. and thanks a lot.

**Comment by Buster14** [comment]
Hi, I'm still getting this on my latest MA installation (installed yesterday)
My HAOS is 8.2, any idea?
I can't find above code which is supposed to be changed in init.py
```
Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 119, in async_setup_entry
    f"with Home Assistant version {manifest['ha_version']} (or higher)."
KeyError: 'ha_version'
```

**Comment by OzGav** [comment]
8.2 is the OS version. What is the HA version? It must be 2022.8.x or newer

**Comment by Buster14** [comment]
Thanks, updating it and now it works.
Btw is there any way to add playlist button on lovelace using this?
So that when pressed it automatically play that particular playlist.

**Comment by OzGav** [comment]
https://github.com/music-assistant/hass-music-assistant/discussions/710 Look at how do I start a playlist with a script

**Comment by Buster14** [comment]
Hmmm script doesn't seem to work, is it currently not working on this version then?
