### ISSUE TITLE
MASS: no connection to internal ip via http

### ISSUE THREAD

**Issue by thomas-svrts** [music-assistant/hass-music-assistant#898]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I'm using a duckdns setup with sonos integrations. 

So I can only access my instance over the duckdns url (because that's the only dns in my certificate).

![image](https://user-images.githubusercontent.com/81048302/188600811-34e6f439-ded1-441e-aa29-c248bbabe1b0.png)

If I connect through https://192.168.10.7 via a browser it complains about the certificate not being correct (ignore the error lets me in), but I guess Sonos doesn't do ignoring invalid certificates.
 
![image](https://user-images.githubusercontent.com/81048302/188601008-ac44b8c0-e139-403a-8907-2cc0685a32b2.png)

Connecting via http://192.168.10.7 isn't allowed by my config file, But I thought MASS launched it's own webserver, so http connection to HASS isn't needed.

```
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

```

sometime when using a Spotify playlist the sonos speakers starts playing, but no feedback is given to mass. So I can't see where in the song he is playing.
Playing music from TuneIn Radio station never works. (logs below are from tuneIn to Sonos speaker)

Please advice if this a network problem and how to fix.

### How to reproduce

install duckdns and use the default suggested config
config you http integration on home assistant to use server port 443 and to use the duckdns certificates.

### Relevant log output

```
2022-09-06 11:49:26.925 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547451570736] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
return self._sock.recv_into(b)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.10.227', port=1400): Read timed out. (read timeout=9.5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
await orig_func(hass, connection, msg, mass)
File "/config/custom_components/mass/websockets.py", line 1188, in websocket_play_media
await player_queue.play_media(
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 275, in play_media
await self.play_index(cur_index)
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 542, in play_index
await self.player.play_url(stream.url)
File "/config/custom_components/mass/player_controls.py", line 747, in play_url
await self.hass.loop.run_in_executor(None, _play_url)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/mass/player_controls.py", line 745, in _play_url
soco.play_uri(url, meta=meta, force_radio=ext == "mp3")
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 147, in inner_function
return function(self, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 829, in play_uri
return self.play()
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 147, in inner_function
return function(self, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 744, in play
self.avTransport.Play([("InstanceID", 0), ("Speed", 1)])
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 206, in _dispatcher
return self.send_command(action, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 486, in send_command
response = requests.post(
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.10.227', port=1400): Read timed out. (read timeout=9.5)
2022-09-06 11:49:26.970 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
return self._sock.recv_into(b)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.10.227', port=1400): Read timed out. (read timeout=9.5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 67, in wrapper
result = funct(self, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 109, in poll_track_info
track_info = self.soco.get_current_track_info()
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 1863, in get_current_track_info
response = self.avTransport.GetPositionInfo(
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 206, in _dispatcher
return self.send_command(action, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 486, in send_command
response = requests.post(
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.10.227', port=1400): Read timed out. (read timeout=9.5)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 157, in update_media_from_event
self.set_basic_track_info(update_position=state_changed)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 122, in set_basic_track_info
track_info = self.poll_track_info()
File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 81, in wrapper
raise SonosUpdateError(message) from err
homeassistant.components.sonos.exception.SonosUpdateError: Error calling SonosMedia.poll_track_info on Symfonisk: HTTPConnectionPool(host='192.168.10.227', port=1400): Read timed out. (read timeout=9.5)
2022-09-06 11:49:30.460 WARNING (MainThread) [music_assistant.stream] Got stream request for already running stream: 39f9113b10d04a9ea2c4eb0572419040, playback may be disturbed!
```

### What version of Home Assistant Core are your running

2022.8.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Music Assistant launches its own -internal only- webserver to serve the audio stream to players on the local network on TCP port 8095. The ip-address that is communicated to players is derived from whatever you fill in at the "internal URL" field of the HA config. So it only takes the IP-address from there (and even resolves dns if needed) and ignores everything else.

So in your case this is already configured correctly. In your case the log is a strong indication that it is already using the correct IP: "Got stream request for already running stream" means that the player is actually requesting the stream (so it reached the webserver) but it fails after that.

Looks like the Symfonisk speaker is not reachable by the Sonos integration, hence all those ReadTimeoutErrors.
Maybe simply restart the speaker to make it work again?

Another cause of issues could be if you group Sonos speakers and you target multiple speakers at the same time.
If a Sonos speaker is grouped, send playback command to the "parent" speaker. In a future version of MA we will resolve these issues with grouping and make grouped speakers a more first class citizen of the whole experience.

**Comment by thomas-svrts** [comment]
> Looks like the Symfonisk speaker is not reachable by the Sonos integration, hence all those ReadTimeoutErrors.
Maybe simply restart the speaker to make it work again?

I use the default sonos integration already for a long time. My symfonisk players and my sonos beam never had problems with it.
Via the default media player it works, so I guess no need to restart it.

> Another cause of issues could be if you group Sonos speakers and you target multiple speakers at the same time.
> If a Sonos speaker is grouped, send playback command to the "parent" speaker. In a future version of MA we will resolve these issues with grouping and make grouped speakers a more first class citizen of the whole experience.

That make more sense because I constantly use sonos groups. But normally (and also in the above case) I send the commands to the master. And when I try sending it to my Sonos Beam it gives a similar error:


`2022-09-06 13:52:17.032 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547355752288] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
return self._sock.recv_into(b)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
await orig_func(hass, connection, msg, mass)
File "/config/custom_components/mass/websockets.py", line 1188, in websocket_play_media
await player_queue.play_media(
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 275, in play_media
await self.play_index(cur_index)
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 542, in play_index
await self.player.play_url(stream.url)
File "/config/custom_components/mass/player_controls.py", line 747, in play_url
await self.hass.loop.run_in_executor(None, _play_url)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/mass/player_controls.py", line 745, in _play_url
soco.play_uri(url, meta=meta, force_radio=ext == "mp3")
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 147, in inner_function
return function(self, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 829, in play_uri
return self.play()
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 147, in inner_function
return function(self, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 744, in play
self.avTransport.Play([("InstanceID", 0), ("Speed", 1)])
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 206, in _dispatcher
return self.send_command(action, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 486, in send_command
response = requests.post(
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)
2022-09-06 13:52:17.088 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
return self._sock.recv_into(b)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 67, in wrapper
result = funct(self, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 109, in poll_track_info
track_info = self.soco.get_current_track_info()
File "/usr/local/lib/python3.10/site-packages/soco/core.py", line 1863, in get_current_track_info
response = self.avTransport.GetPositionInfo(
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 206, in _dispatcher
return self.send_command(action, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/soco/services.py", line 486, in send_command
response = requests.post(
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 157, in update_media_from_event
self.set_basic_track_info(update_position=state_changed)
File "/usr/src/homeassistant/homeassistant/components/sonos/media.py", line 122, in set_basic_track_info
track_info = self.poll_track_info()
File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 81, in wrapper
raise SonosUpdateError(message) from err
homeassistant.components.sonos.exception.SonosUpdateError: Error calling SonosMedia.poll_track_info on Woonkamer: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)`

**Comment by marcelveldt** [comment]
Can you please restart the speaker or check the network ?

```
homeassistant.components.sonos.exception.SonosUpdateError: Error calling SonosMedia.poll_track_info on Woonkamer: HTTPConnectionPool(host='192.168.10.219', port=1400): Read timed out. (read timeout=9.5)
```

**Comment by thomas-svrts** [comment]
Did both, network works just fine via hass or sonos app.

**Comment by OzGav** [comment]
We are only providing limited support for people running non standard HA installs. Search the repo for “ kubernetes” and look at the issues where his was mentioned and see if any of those apply to you.

**Comment by erkr** [comment]
Hi
As @OzGav already mentioned, it's hard to support non standard configurations.
But maybe it's worth to shortly look into:

> Hi, i have the feeling that it doesn't use the "internal URL" field but the network adapter 

That would be weird, standard or not.

**Comment by Xhelliom** [comment]
Hi, thank you for your answer. I totally understand that non standard configuration are not supported, of course :).
And you also mention that docker installation must be in host network mode, which is not my case.

The comment was more to notify that it looks like it's not following the documentation that's saying it's using the "internal url" field. 

So if your able to resolve this issue, good for me :) if not, I'll buy a raspberry ;)

**Comment by erkr** [comment]
Hi @marcelveldt 
Please have a quick look. In the thread above you find an example where the connect error contains another IP address than the configured internal IP. Although this is a non standaard configuration, that would indicate a bug, right?

Best Eric

**Comment by marcelveldt** [comment]
Kubernetes is not officially supported by Home Assistant so it is very hard for us to support these kind of deployments. I'd rather focus both development and support focus on Home Assistant OS based installs (and maybe also the official docker container but that one is already more tricky to support) because that is what like 90% of the users run.

That said, there's some logic in place that derives the correct internal IP from the internal URL.
If that does not work correctly you will have issue with other things too, for example with TTS.

So my advice would be to make sure that the main issue is fixed. I have heard a few times that playing with the network settings (change from static to DHCP and vice versa) can help solving these kind of strange issues.

**Comment by erkr** [comment]
@thomas-svrts 
The issue derailed a little by others. Can you please indicate if your original Sonos issue is still actual?
Best Eric

**Comment by thomas-svrts** [comment]
Yes still the same. 

playing tuneIn radio never works. Spotify works, but I never see progress of the song in MA.

**Comment by erkr** [comment]
@thomas-svrts 
Thanks for confirming the probleem is not resolved. I leave the issue open then.

**Comment by OzGav** [comment]
Please advise if this is still an issue in MA v2

**Comment by thomas-svrts** [comment]
Ik works in v2
